import { PlaceableObject } from "../models";

type CatalogEntry = Omit<PlaceableObject, "id">;

export const CATALOG: CatalogEntry[] = [
  // ── Medieval ──────────────────────────────────────────
  {
    name: "Casa de madera",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Vivienda sencilla de madera y paja",
  },
  {
    name: "Muralla de piedra",
    sizeX: 1,
    sizeY: 1,
    category: "edificio",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Segmento de muralla defensiva",
  },
  {
    name: "Torre de vigilancia",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 50,
    isFree: false,
    description: "Atalaya de piedra para vigía",
  },
  {
    name: "Castillo",
    sizeX: 5,
    sizeY: 5,
    category: "edificio",
    era: "medieval",
    price: 200,
    isFree: false,
    description: "Fortaleza medieval con torres y almenas",
  },
  {
    name: "Herrería",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "medieval",
    price: 80,
    isFree: false,
    description: "Taller de forja y metalistería",
  },
  {
    name: "Pozo de agua",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Pozo de piedra con cubo y cuerda",
  },
  {
    name: "Antorcha",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Antorcha encendida sobre soporte de hierro",
  },
  {
    name: "Taberna",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 60,
    isFree: false,
    description: "Local de bebidas y comida con ambiente acogedor",
  },
  {
    name: "Iglesia medieval",
    sizeX: 3,
    sizeY: 4,
    category: "edificio",
    era: "medieval",
    price: 120,
    isFree: false,
    description: "Templo de piedra con campanario",
  },
  {
    name: "Granero",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "medieval",
    price: 40,
    isFree: false,
    description: "Almacén de grano y cosechas",
  },
  {
    name: "Establo",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 70,
    isFree: false,
    description: "Refugio para caballos y animales de carga",
  },
  {
    name: "Carreta",
    sizeX: 2,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Carro de madera tirado por bueyes",
  },
  {
    name: "Barril",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Barril de madera para almacenar vino o cerveza",
  },
  {
    name: "Roble grande",
    sizeX: 2,
    sizeY: 2,
    category: "naturaleza",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Árbol robusto de amplia copa",
  },
  {
    name: "Arbusto silvestre",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Arbusto frondoso del bosque",
  },

  // ── Colonial / Clásico ────────────────────────────────
  {
    name: "Granja",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Granja con campos de cultivo",
  },
  {
    name: "Molino de viento",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "colonial",
    price: 60,
    isFree: false,
    description: "Molino tradicional de aspas de madera",
  },
  {
    name: "Mansión colonial",
    sizeX: 4,
    sizeY: 4,
    category: "edificio",
    era: "colonial",
    price: 150,
    isFree: false,
    description: "Residencia señorial con columnas y jardín",
  },
  {
    name: "Fuente clásica",
    sizeX: 2,
    sizeY: 2,
    category: "decoracion",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Fuente de piedra ornamental",
  },
  {
    name: "Farola de gas",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Farola alimentada por gas",
  },
  {
    name: "Puente de piedra",
    sizeX: 4,
    sizeY: 1,
    category: "edificio",
    era: "colonial",
    price: 100,
    isFree: false,
    description: "Puente de arcos de piedra sobre río",
  },
  {
    name: "Ayuntamiento",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "colonial",
    price: 140,
    isFree: false,
    description: "Sede del gobierno local con fachada clásica",
  },
  {
    name: "Biblioteca",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "colonial",
    price: 90,
    isFree: false,
    description: "Edificio de saber con estanterías de libros",
  },
  {
    name: "Mercado",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Plaza de comercio con puestos de venta",
  },
  {
    name: "Banco de hierro",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Banco decorativo de hierro forjado",
  },
  {
    name: "Reloj de sol",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "colonial",
    price: 30,
    isFree: false,
    description: "Reloj solar de piedra sobre pedestal",
  },
  {
    name: "Arco decorativo",
    sizeX: 2,
    sizeY: 1,
    category: "decoracion",
    era: "colonial",
    price: 50,
    isFree: false,
    description: "Arco triunfal de piedra ornamentada",
  },
  {
    name: "Jardín formal",
    sizeX: 2,
    sizeY: 2,
    category: "naturaleza",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Jardín simétrico con parterres de flores",
  },
  {
    name: "Seto recortado",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Seto ornamental recortado en forma geométrica",
  },
  {
    name: "Ciprés",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Árbol esbelto y vertical típico de jardines clásicos",
  },

  // ── Industrial ────────────────────────────────────────
  {
    name: "Fábrica",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Fábrica con chimeneas humeantes",
  },
  {
    name: "Estación de tren",
    sizeX: 5,
    sizeY: 2,
    category: "edificio",
    era: "industrial",
    price: 120,
    isFree: false,
    description: "Estación ferroviaria con andenes",
  },
  {
    name: "Almacén industrial",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "industrial",
    price: 40,
    isFree: false,
    description: "Almacén de ladrillo y acero",
  },
  {
    name: "Farola eléctrica",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Farola con bombilla eléctrica",
  },
  {
    name: "Chimenea",
    sizeX: 1,
    sizeY: 1,
    category: "edificio",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Chimenea de ladrillo humeante",
  },
  {
    name: "Puente de hierro",
    sizeX: 5,
    sizeY: 1,
    category: "edificio",
    era: "industrial",
    price: 130,
    isFree: false,
    description: "Puente de estructura metálica remachada",
  },
  {
    name: "Central eléctrica",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "industrial",
    price: 100,
    isFree: false,
    description: "Planta generadora de electricidad",
  },
  {
    name: "Depósito de agua",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "industrial",
    price: 60,
    isFree: false,
    description: "Torre de agua elevada sobre estructura metálica",
  },
  {
    name: "Buzón",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Buzón de correo de hierro fundido",
  },
  {
    name: "Señal de tráfico",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Señal vial de metal sobre poste",
  },
  {
    name: "Cañón decorativo",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 50,
    isFree: false,
    description: "Cañón antiguo de exhibición",
  },
  {
    name: "Vagón de tren",
    sizeX: 2,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 70,
    isFree: false,
    description: "Vagón de carga sobre vías",
  },
  {
    name: "Grúa",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "industrial",
    price: 80,
    isFree: false,
    description: "Grúa de construcción industrial",
  },
  {
    name: "Parque urbano",
    sizeX: 3,
    sizeY: 3,
    category: "naturaleza",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Zona verde con bancos y caminos de gravilla",
  },
  {
    name: "Árbol podado",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Árbol urbano con copa redondeada",
  },

  // ── Moderno ───────────────────────────────────────────
  {
    name: "Casa moderna",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Vivienda contemporánea con diseño minimalista",
  },
  {
    name: "Rascacielos pequeño",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "moderno",
    price: 180,
    isFree: false,
    description: "Edificio de oficinas de varias plantas",
  },
  {
    name: "Hospital",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "moderno",
    price: 150,
    isFree: false,
    description: "Centro hospitalario moderno",
  },
  {
    name: "Semáforo",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Semáforo de tráfico con tres luces",
  },
  {
    name: "Centro comercial",
    sizeX: 5,
    sizeY: 4,
    category: "edificio",
    era: "moderno",
    price: 200,
    isFree: false,
    description: "Gran superficie de tiendas y ocio",
  },
  {
    name: "Estadio",
    sizeX: 6,
    sizeY: 6,
    category: "edificio",
    era: "moderno",
    price: 300,
    isFree: false,
    description: "Estadio deportivo con gradas",
  },
  {
    name: "Gasolinera",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Estación de servicio con surtidores",
  },
  {
    name: "Comisaría",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "moderno",
    price: 120,
    isFree: false,
    description: "Comisaría de policía local",
  },
  {
    name: "Parada de bus",
    sizeX: 2,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Marquesina de parada de autobús",
  },
  {
    name: "Contenedor",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Contenedor de reciclaje urbano",
  },
  {
    name: "Escultura abstracta",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 60,
    isFree: false,
    description: "Obra de arte contemporáneo en metal",
  },
  {
    name: "Piscina",
    sizeX: 3,
    sizeY: 2,
    category: "decoracion",
    era: "moderno",
    price: 80,
    isFree: false,
    description: "Piscina con agua cristalina",
  },
  {
    name: "Helipuerto",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "moderno",
    price: 160,
    isFree: false,
    description: "Plataforma de aterrizaje para helicópteros",
  },
  {
    name: "Antena parabólica",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 40,
    isFree: false,
    description: "Antena de comunicaciones por satélite",
  },
  {
    name: "Palmera",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Palmera tropical decorativa",
  },
  {
    name: "Jardín zen",
    sizeX: 2,
    sizeY: 2,
    category: "naturaleza",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Jardín minimalista con arena y piedras",
  },

  // ── Futurista ─────────────────────────────────────────
  {
    name: "Torre de energía",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Estructura generadora de energía limpia",
  },
  {
    name: "Cúpula habitable",
    sizeX: 4,
    sizeY: 4,
    category: "edificio",
    era: "futurista",
    price: 250,
    isFree: false,
    description: "Hábitat cerrado con ecosistema autosuficiente",
  },
  {
    name: "Laboratorio cuántico",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 200,
    isFree: false,
    description: "Centro de investigación de tecnología avanzada",
  },
  {
    name: "Holograma proyector",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Dispositivo que proyecta hologramas decorativos",
  },
  {
    name: "Hangar de naves",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 180,
    isFree: false,
    description: "Hangar para naves y vehículos voladores",
  },
  {
    name: "Reactor de fusión",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 220,
    isFree: false,
    description: "Reactor de energía de fusión nuclear",
  },
  {
    name: "Módulo residencial",
    sizeX: 2,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Vivienda modular con tecnología avanzada",
  },
  {
    name: "Estación espacial mini",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 280,
    isFree: false,
    description: "Estación orbital en miniatura",
  },
  {
    name: "Teletransportador",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 100,
    isFree: false,
    description: "Plataforma de teletransporte cuántico",
  },
  {
    name: "Robot guardián",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 80,
    isFree: false,
    description: "Autómata de seguridad estacionario",
  },
  {
    name: "Cristal energético",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Cristal brillante que emana energía",
  },
  {
    name: "Nave estacionada",
    sizeX: 2,
    sizeY: 2,
    category: "decoracion",
    era: "futurista",
    price: 150,
    isFree: false,
    description: "Nave espacial aparcada en plataforma",
  },
  {
    name: "Dron de carga",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 60,
    isFree: false,
    description: "Dron autónomo de transporte de mercancías",
  },
  {
    name: "Árbol bioluminiscente",
    sizeX: 1,
    sizeY: 1,
    category: "naturaleza",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Árbol modificado genéticamente que brilla en la oscuridad",
  },
  {
    name: "Jardín hidropónico",
    sizeX: 2,
    sizeY: 2,
    category: "naturaleza",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Jardín de cultivo sin suelo con iluminación LED",
  },
];
