import { PlaceableObject } from "../models";

type CatalogEntry = Omit<PlaceableObject, "id">;

export const CATALOG: CatalogEntry[] = [
  // ── Medieval ──────────────────────────────────────────
  {
    name: "Casa de madera",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Vivienda sencilla de madera y paja",
  },
  {
    name: "Muralla de piedra",
    sizeX: 1,
    sizeY: 1,
    category: "edificio",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Segmento de muralla defensiva",
  },
  {
    name: "Torre de vigilancia",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "medieval",
    price: 50,
    isFree: false,
    description: "Atalaya de piedra para vigía",
  },
  {
    name: "Castillo",
    sizeX: 5,
    sizeY: 5,
    category: "edificio",
    era: "medieval",
    price: 200,
    isFree: false,
    description: "Fortaleza medieval con torres y almenas",
  },
  {
    name: "Herrería",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "medieval",
    price: 80,
    isFree: false,
    description: "Taller de forja y metalistería",
  },
  {
    name: "Pozo de agua",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Pozo de piedra con cubo y cuerda",
  },
  {
    name: "Antorcha",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "medieval",
    price: 0,
    isFree: true,
    description: "Antorcha encendida sobre soporte de hierro",
  },

  // ── Colonial / Clásico ────────────────────────────────
  {
    name: "Granja",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Granja con campos de cultivo",
  },
  {
    name: "Molino de viento",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "colonial",
    price: 60,
    isFree: false,
    description: "Molino tradicional de aspas de madera",
  },
  {
    name: "Mansión colonial",
    sizeX: 4,
    sizeY: 4,
    category: "edificio",
    era: "colonial",
    price: 150,
    isFree: false,
    description: "Residencia señorial con columnas y jardín",
  },
  {
    name: "Fuente clásica",
    sizeX: 2,
    sizeY: 2,
    category: "decoracion",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Fuente de piedra ornamental",
  },
  {
    name: "Farola de gas",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "colonial",
    price: 0,
    isFree: true,
    description: "Farola alimentada por gas",
  },

  // ── Industrial ────────────────────────────────────────
  {
    name: "Fábrica",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Fábrica con chimeneas humeantes",
  },
  {
    name: "Estación de tren",
    sizeX: 5,
    sizeY: 2,
    category: "edificio",
    era: "industrial",
    price: 120,
    isFree: false,
    description: "Estación ferroviaria con andenes",
  },
  {
    name: "Almacén industrial",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "industrial",
    price: 40,
    isFree: false,
    description: "Almacén de ladrillo y acero",
  },
  {
    name: "Farola eléctrica",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "industrial",
    price: 0,
    isFree: true,
    description: "Farola con bombilla eléctrica",
  },

  // ── Moderno ───────────────────────────────────────────
  {
    name: "Casa moderna",
    sizeX: 3,
    sizeY: 2,
    category: "edificio",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Vivienda contemporánea con diseño minimalista",
  },
  {
    name: "Rascacielos pequeño",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "moderno",
    price: 180,
    isFree: false,
    description: "Edificio de oficinas de varias plantas",
  },
  {
    name: "Hospital",
    sizeX: 4,
    sizeY: 3,
    category: "edificio",
    era: "moderno",
    price: 150,
    isFree: false,
    description: "Centro hospitalario moderno",
  },
  {
    name: "Semáforo",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "moderno",
    price: 0,
    isFree: true,
    description: "Semáforo de tráfico con tres luces",
  },

  // ── Futurista ─────────────────────────────────────────
  {
    name: "Torre de energía",
    sizeX: 2,
    sizeY: 2,
    category: "edificio",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Estructura generadora de energía limpia",
  },
  {
    name: "Cúpula habitable",
    sizeX: 4,
    sizeY: 4,
    category: "edificio",
    era: "futurista",
    price: 250,
    isFree: false,
    description: "Hábitat cerrado con ecosistema autosuficiente",
  },
  {
    name: "Laboratorio cuántico",
    sizeX: 3,
    sizeY: 3,
    category: "edificio",
    era: "futurista",
    price: 200,
    isFree: false,
    description: "Centro de investigación de tecnología avanzada",
  },
  {
    name: "Holograma proyector",
    sizeX: 1,
    sizeY: 1,
    category: "decoracion",
    era: "futurista",
    price: 0,
    isFree: true,
    description: "Dispositivo que proyecta hologramas decorativos",
  },
];
